on:
  push:
  pull_request:
    paths: 
      - '**.ts'
      - '**.scss'

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run check
    
    - name: Run tests
      run: npm run test

    - name: Delete previous build
      run: rm -rf lib

    - name: Build
      run: npm run build

    - uses: actions/upload-artifact@v3
      with:
        path: ./lib

    - name: Configure Git
      run: |
        git config --global user.name "RuMont"
        git config --global user.email "rumont98@gmail.com"

    - name: Commit and Push Changes
      if: ${{ github.actor != 'github-actions[bot]' }}
      run: |
        git add .
        git commit -m "Wrapping"
        git push https://${{ secrets.PAT_TOKEN }}N@github.com/RuMont/alerts.git HEAD:master